// Auto-generated by Supabase — run `supabase gen types typescript` after migrations
// Placeholder until ETAPA 0.3 migrations are applied
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
  }
}
